entryPoints:
    web:
        address: ":80"
        http:
            redirections:
                entryPoint:
                    to: websecure
                    scheme: https
    websecure:
        address: ":443"
        http:
            tls:
                certResolver: default
                domains:
                    - main: "*.{{env "TRAEFIK_BASE_HOST"}}"
                    - main: {{env "TRAEFIK_BASE_HOST"}}
    nosecure:
        address: ":8088"

providers:
    docker:
        endpoint: unix:///var/run/docker.sock
        exposedByDefault: false
    file:
        filename: "/traefik.yaml"
        watch: true

api:
    dashboard: true
    insecure: true

ping:
    entryPoint: web

log:
    level: WARN

certificatesResolvers:
    default:
        acme:
            email: `{{env "AMCE_EMAIL"}}`
            storage: "/data/acme.json"
            tlsChallenge: {}
            httpChallenge:
                entryPoint: web
            dnsChallenge:
                provider: manual
                delayBeforeCheck: 300

http:
    middlewares:
        secured:
            basicAuth:
                removeHeader: true
                users:
                    - `{{env "TRAEFIK_BASIC_AUTH"}}`

        cors:
            headers:
                accessControlAllowMethods:
                    - GET
                    - POST
                    - PUT
                    - DELETE
                    - OPTIONS
                accessControlAllowOriginList:
                    - "*"
                accessControlAllowHeaders:
                    - "Origin"
                    - "X-Requested-With"
                    - "Content-Type"
                    - "Accept"
                    - "Token"
                    - "Authorization"
                accessControlMaxAge: 100
                addVaryHeader: true

    serversTransports:
        insecureHttps:
            insecureSkipVerify: true

    services:
        webmin:
            loadBalancer:
                servers:
                    - url: `{{env "HOST_IP"}}`:10000

