name: Custom infrastructure workflow

on:
  push:
    branches:
      - main

env:
  DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}

jobs:
  deploy:
    name: Deploy images on the destination server
    if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Copy env vars
        uses: SpicyPizza/create-envfile@v1.3
        with:

          envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          envkey_TRAEFIK_BASIC_AUTH: ${{ secrets.TRAEFIK_BASIC_AUTH }}
          envkey_TRAEFIK_API_HOST: ${{ secrets.TRAEFIK_API_HOST }}
          envkey_IP_WHITELIST: ${{ secrets.IP_WHITELIST }}
          envkey_ADMINER_HOST: "adminer.dev.andyi95.com"
          envkey_COMPOSE_PROJECT_NAME: "infra"
          file_name: .env.dist
          fail_on_empty: false

      - name: Copy files to server
        run: |
          mkdir ../build
          cp -TR . ../build
          tar -cvf deploy.tar ../build/

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "deploy.tar"
          target: "./"

      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        env:
          IP_WHITELIST: ${{ secrets.IP_WHITELIST }}
          TRAEFIK_BASIC_AUTH: ${{ secrets.TRAEFIK_BASIC_AUTH }}
          TRAEFIK_API_HOST: ${{ secrets.TRAEFIK_API_HOST }}
          VPN_IPSEC_PSK: ${{ secrets.VPN_IPSEC_PSK }}
          VPN_USER: ${{ secrets.VPN_USER }}
          VPN_PASSWORD: ${{ secrets.VPN_PASSWORD }}
          VPN_ADDL_USERS: ${{ secrets.VPN_ADDL_USERS }}
          VPN_ADDL_PASSWORDS: ${{ secrets.VPN_ADDL_PASSWORDS }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          envs: IP_WHITELIST,TRAEFIK_BASIC_AUTH,TRAEFIK_API_HOST,VPN_IPSEC_PSK,VPN_USER,VPN_PASSWORD,VPN_ADDL_USERS,VPN_ADDL_PASSWORDS
          script: |
            mkdir -p infra
            tar -xvf deploy.tar --strip-components=1 -C infra/
            echo "Building stage"
            echo " "
            cd infra
            bash -c '
            set -a;
            source .env.dist;
            source .env;
            export DOCKER_USER="1000:1000"
            (printenv | grep -v "^_=" | sort)
            ' > .env
            docker-compose up -d --build --force-recreate --remove-orphans

      - name: send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Report on the last run of ${{ github.workflow }}.
            ${{ github.job }} in workflow ${{ github.action }} from repo ${{ github.repository }} has finished with status ${{ job.status }}.
